### ISSUE TITLE
database log files are stored with internal owners and permissions

### ISSUE THREAD

**Issue by exaSR** [exasol/exasol-testcontainers#55]
#### Problem description
The new feature `ExasolContainer.withClusterLogsPath` changes permissions of the given Path and creates files with user `id 500` or even root.

#### Warnings / Impact
* Passing `Paths.get(".")` will *really* mess up your code directory
* As non-privileged user you will need another docker container to clean up that mess.

#### Expected behavior
* Log files are owned and readable by user executing the test.

**Comment by redcatbear** [comment]
Since this internally uses the [`.withClasspathResourceMapping(...)`](https://www.testcontainers.org/features/files/) feature of the general Test containers, I don't think we can influence this in our own code. That would be an issue ticket for the test container project.

I will check if such a ticket exists. If yes, I will link it here, otherwise I will create one.

**Comment by redcatbear** [comment]
Created ticket in test container main repository: https://github.com/testcontainers/testcontainers-java/issues/2762

Although I think the functionality will be too hard too implement, since it requires a shadow copy of the files in the container.

**Comment by redcatbear** [comment]
@exaSR: if the test container team tells us that a change in the resource mapping is not feasible, how about a "copyServerLogs()" method?

**Comment by exaSR** [comment]
@redcatbear: I'd be happy if `ExaOperationEmulator` would provide the "download debug logs" functionality :)

**Comment by redcatbear** [comment]
I see. In that case, let me turn that into a feature request: #61

**Comment by redcatbear** [comment]
There is a way to start a Docker container as non-root:

- https://www.testcontainers.org/features/advanced_options/#customizing-the-container
- Question came up in testcontainers/testcontainers-java#2590

I highly doubt though that with the Exasol container requiring privileged mode, starting it the container as regular user would work.

I will close this ticket, since #61 is the better alternative.
