### ISSUE TITLE
Purge BucketFS

### ISSUE THREAD

**Issue by jakobbraun** [exasol/exasol-testcontainers#74]
In reuse mode, ETC purges the Exasol database on startup. Until now BucketFS is not purged. This is however important to guarantee isolation between tests.

**Comment by kaklakariada** [comment]
Implementing this is not possible because we can't detect from the log files when the deletion of a file is synchronized across the cluster (see also https://github.com/exasol/bucketfs-java/issues/42).

When tests upload the same file shortly after it was deleted (<10s) the request will fail with status 423. Waiting around 10s is the only known workaround for Exasol running in a docker container. 

We decided to not implement this. If you need to purge BucketFS you can use the new recursive listing added in https://github.com/exasol/bucketfs-java/issues/57.
