### ISSUE TITLE
Let `exasol-testcontainers` automatically upload jar from `target` folder

### ISSUE THREAD

**Issue by AnastasiiaSergienko** [exasol/exasol-testcontainers#9]
As a user I would like to have a convenience method that allows me to upload a jar from `target` folder to the container without hard-coding jar's name.

**Comment by redcatbear** [comment]
There are a few things that we need to keep in mind if we want to implement this.

1. There can be multiple versions of a JAR file in the target directory
1. There can be multiple variants of a JAR of the same version in the target directory (e.g. a JAR that contains all dependencies)

So it is quite dangerous just uploading a JAR from the target directory without any kind of validation.

The absolute minimum would be checking conventions.

**Comment by redcatbear** [comment]
The simplest possible solution would be to provide a regular expression for the JAR name. Deployment only happens if there is exactly one match for that name.

The we turn the version number into wildcards. If only one version is in the target directory, we can proceed, otherwise we bail out just to be safe.
